import type { Metadata } from "next";

import Header from "./Header/page"

import Footer from "./Footer/page"

import PreFooter from "./PreFooter/page";
// import { Inter } from "next/font/google";
// import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      <Header />
        {children}
        
      <Footer />

      </body>
    </html>
  );
}




{/* <body className={inter.className}>{children}</body> */}